# Generated by Django 6.0.4 on 2026-05-21 11:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(help_text='Название услуг', max_length=255, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание ваших услуги', verbose_name='Описание')),
                ('price', models.PositiveIntegerField(help_text='Стоимость: минимально 100р', validators=[django.core.validators.MinValueValidator(100)], verbose_name='Цена')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(help_text='Название задачи', max_length=255, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание ваших задачи', verbose_name='Описание')),
                ('price', models.PositiveIntegerField(help_text='Стоимость: минимально 100р', validators=[django.core.validators.MinValueValidator(100)], verbose_name='Цена')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
