# Generated by Django 6.0.3 on 2026-03-29 08:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Назоваите ваш вид услуг', max_length=255, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание ваших услуг', verbose_name='Описание')),
                ('price', models.PositiveIntegerField(help_text='Стоимость', validators=[django.core.validators.MinValueValidator(100)], verbose_name='Цена')),
            ],
        ),
    ]
