# Generated by Django 6.0.3 on 2026-04-17 10:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_mesege_offer_messege'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='offer',
            unique_together={('service', 'executor')},
        ),
    ]
