# Generated by Django 6.0.4 on 2026-05-14 12:34

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_delete_offer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Описание ваших услуги', verbose_name='Описание'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('title', models.CharField(help_text='Название задачи', max_length=255, verbose_name='Название')),
                ('description', models.TextField(help_text='Описание ваших задачи', verbose_name='Описание')),
                ('price', models.PositiveIntegerField(help_text='Стоимость: минимально 100р', validators=[django.core.validators.MinValueValidator(100)], verbose_name='Цена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'abstract': False,
                'unique_together': {('user', 'title')},
            },
        ),
    ]
