# Generated by Django 6.0.4 on 2026-05-23 10:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_ad', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='pending', max_length=20)),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('proposed_price', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(verbose_name='Сопроводительное письмо')),
            ],
        ),
        migrations.CreateModel(
            name='TaskChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_ad', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TaskOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('accepted', 'Принят'), ('rejected', 'Отклонен')], default='pending', max_length=20)),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
                ('proposed_price', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(verbose_name='Сопроводительное письмо')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceMessage',
            fields=[
                ('basemessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.basemessage')),
            ],
            bases=('chat.basemessage',),
        ),
        migrations.CreateModel(
            name='TaskMessage',
            fields=[
                ('basemessage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='chat.basemessage')),
            ],
            bases=('chat.basemessage',),
        ),
    ]
