# Generated by Django 6.0.4 on 2026-05-23 10:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0001_initial'),
        ('shop', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basemessage',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicechat',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='executor'),
        ),
        migrations.AddField(
            model_name='serviceoffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.service', verbose_name='service'),
        ),
        migrations.AddField(
            model_name='servicechat',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.serviceoffer'),
        ),
        migrations.AddField(
            model_name='taskchat',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskoffer',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='executor'),
        ),
        migrations.AddField(
            model_name='taskoffer',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.task', verbose_name='task'),
        ),
        migrations.AddField(
            model_name='taskchat',
            name='offer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='chat.taskoffer'),
        ),
        migrations.AddField(
            model_name='servicemessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.servicechat'),
        ),
        migrations.AddField(
            model_name='taskmessage',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.taskchat'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceoffer',
            unique_together={('product', 'executor')},
        ),
        migrations.AlterUniqueTogether(
            name='taskoffer',
            unique_together={('product', 'executor')},
        ),
    ]
