# Generated by Django 6.0.4 on 2026-05-06 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='end_date',
        ),
    ]
