# Generated by Django 6.0.4 on 2026-06-02 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicechat',
            name='name',
            field=models.CharField(default='name', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='taskchat',
            name='name',
            field=models.CharField(default='name', max_length=500),
            preserve_default=False,
        ),
    ]
