# Generated by Django 6.0.3 on 2026-04-17 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='mesege',
            new_name='messege',
        ),
    ]
