# Generated by Django 6.0.3 on 2026-04-22 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_service_slug_alter_service_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Offer',
        ),
    ]
