# Generated by Django 6.0.3 on 2026-04-06 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_avatar_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='avatars/5856.jpg', upload_to='avatars/', verbose_name='Аватарка'),
        ),
    ]
