# Generated by Django 6.0.3 on 2026-04-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='5856.jpg', upload_to='avatars/', verbose_name='Аватарка'),
        ),
    ]
