# Generated by Django 6.0.4 on 2026-04-30 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_profile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
    ]
